version: '2'
services:
  pytorch:  # 服务名称，可自定义
    deploy:  # 部署资源，此处部署了1个GPU
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: 32gb  # 最大页大小
    container_name: pytorch-zd  # 容器名，可自定义，不要和已经运行的容器重复
    image: "anibali/pytorch"  # 镜像名称
    volumes:  # 挂载目录
     - /data_zfs/fast/zhaodong/:/app/zhaodong  # 将容器内的/root/data目录挂载到宿主机当前工作目录下的data文件夹（如没有会新建）。可自行修改      实体:容器

    environment:  # 设置环境变量
     - DISPLAY=unix$DISPLAY
    command: /bin/bash  # 启动时执行的命令
    tty: true
